### ISSUE TITLE
Longer than 7 character filenames fail to play

### ISSUE THREAD

**Issue by zhaoyu3517** [MartinNohr/LedImagePainter#25]
I found that if the file name exceeds 7 letters, it will fail to play.There are too many pictures in the SD card and it will crash.

**Comment by zhaoyu3517** [comment]
Sorry, I found the cause of the problem.

**Comment by MartinNohr** [comment]
I have a new version of this using the TTGO T-Display. It has a nice color screen. 
I fixed the SD code so it can read long filenames and have as many files as you want in the TTGO version. This version has a limit of I think 20 files in each folder. I removed that limit in the TTGO version. I might fix this version also. Keep checking for a new post.
The TTGO version is here: https://github.com/MartinNohr/MagicImageWand

**Comment by MartinNohr** [comment]
I'll reopen this until I fix the file limits.

**Comment by MartinNohr** [comment]
I fixed the code so longer filenames will work correctly. I didn't change the code version number.
